# $HOME/.config/hypr/hyprland.conf
#
# ┳ ┳┓ ┳┳━┓┳━┓┳━┓┳━┓┳━┓┳━┓┳━┓
# ┃━┫┗┏┛┃━┛┃┳┛┃━┛┃━┫┃━┛┣━ ┃┳┛
# ┛ ┻ ┛ ┛  ┛┗┛┛  ┛ ┛┛  ┻━┛┛┗┛
# Hyprpaper config
#
# GitHub:       https://github.com/xcession/dotfiles
# Maintainer:   Пэйнт (Tharawut Paripaiboon)

wallpaper {
  monitor =
  path = ~/.wallpaper.jpg
  fit_mode = cover
}

# IPC is disabled for better battery life
ipc = false

# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
