#!/bin/sh

# $HOME/.config/bspwm/bspwmrc
#
# ┳━┓┓━┓┳━┓┓ ┳┏┏┓
# ┃━┃┗━┓┃━┛┃┃┃┃┃┃
# ┛━┛━━┛┛  ┗┻┛┛ ┛
# bspwm config
#
# GitHub:       https://github.com/xcession/dotfiles
# Maintainer:   Пэйнт (Tharawut Paripaiboon)

#: Autostart {{{

# detect external monitor
# bash $HOME/bin/mon_toggle

# polkit
/usr/bin/lxpolkit &

# desktop notification
/usr/bin/dunst &

# network manager
/usr/bin/nm-applet &

# compositor
/usr/bin/picom -b &

# polybar
bash $HOME/.config/polybar/launch.sh &

#: }}}

#: Output {{{

# restore desktop wallpaper
/usr/bin/nitrogen --restore &

#: }}}

#: Input {{{

pgrep -x sxhkd > /dev/null || sxhkd &

# keyboard layouts
setxkbmap -layout gb,us,th -option grp:alt_shift_toggle &

# thinkpad trackpoint
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Enabled" 1 &
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Middle Emulation Enabled" 1 &

# thinkpad trackpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Middle Emulation Enabled" 1 &

# MX Master 2S
xinput set-prop "pointer:Logitech MX Master 2S" "Device Enabled" 1 &
xinput set-prop "pointer:Logitech MX Master 2S" "libinput Natural Scrolling Enabled" 1 &

#: }}}

#: Workspaces {{{

# bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X
# bspc monitor DP2 -d VI VII VIII IX X

#: }}}

#: Border & Gaps {{{

bspc config border_width         2
bspc config window_gap          10
bspc config normal_border_color         '#232530'
bspc config focused_border_color        '#29d398'
bspc config presel_border_color         '#16161c'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#: }}}

#: pointer and focus {{{

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#: }}}

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# vim:fileencoding=utf-8:ft=sh:foldmethod=marker
